questions = [
    'Your partner does not want a kid(s)?',
    'Your partner has a kid(s)?',
    'Your partner has been previously divorced?',
    'Your partners parents are divorced?',
    'Your partner has bad hygiene?',
    'Your partner is not athletic?',
    'Your partner did not complete high school?',
    'Your partner did not attend University?',
    'Your partner is unemployed?',
    'Your partner still lives at home?',
    'Your partner smokes?',
    'Your partner drinks alcohol?',
    'Your partner vapes?',
    'Your partner has cheated in the past?',
    'Your partner is still close with an ex partner of theirs?',
    'Your partner is clingy?',
    'Your partner is dishonest?',
    'Your partner is vegan?',
    'Your partner keeps you a secret?',
    'Your partner is excessively jealous?',
]